spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver #org.mariadb.jdbc.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1 #jdbc:mariadb://127.0.0.1:3306/jpa
    username: sa #root
    password: #tmzkdl10@M
  jpa:
    hibernate:
      ddl-auto: create #update #create-drop
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy #Entity naming 전략 underScope
    properties:
      hibernate:
        show_sql: true
        format_sql: true

log:
  config:
    path: /logs/test
    filename: test_log

logging:
  level:
    root: info
